name: ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: [ubuntu-latest, windows-latest] 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install ruff package
      run: |
        python -m pip install --upgrade pip
        pip install --user ruff
    - name: Run ruff package
      run: ruff --format=github --target-version=py37 .
